# Generated by Django 4.2.2 on 2023-07-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='ccount',
            new_name='count',
        ),
    ]
