# Generated by Django 4.2.2 on 2023-07-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_ccount_reservation_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='booking_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
