# Generated by Django 4.2.2 on 2023-07-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_geekscreate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeeksCreate',
            new_name='GeeksModel',
        ),
    ]
